---
- hosts: webservers
  gather_facts: false
  become: true

  tasks:
  - name: Install nginx
    dnf:
      name: nginx
      state: latest

  - name: Enable nginx service
    service:
      name: nginx
      enabled: yes
   
  - name: Create directory for content
    file:
      path: /var/www/html/hello-world
      state: directory
      mode: '0755'

  - name: Download "index.html" file with "hello world" content
    get_url:
      url: "https://raw.githubusercontent.com/tellis4151/terraform/refs/heads/main/templates/index.html.j2"
      dest: /var/www/html/hello-world/index.html

#  - name: Copy "index.hthml to default Nginx location"
#    copy:
#      src: /var/www/html/hello-world/index.html
#      dest: /var/www/html/index.html
#      mode: '0644'
#      remote_src: true

#  - name: Enable default Nginx website
#    file:
#      src: /etc/nginx/sites-available/default
#      path: /etc/nginx/sites-enabled/default
#      state: link

#  - name: Restart Nginx
#    service: 
#      name: nginx
#      state: started
