---
- hosts: webservers
  gather_facts: false
  become: true

  tasks:
    - name: Start score sum
      ansible.builtin.set_fact:
        student_score: 0

    - name: Check webservers group
      ansible.builtin.command: ping
      register: task1

    - name: Print task 1 variable
      debug:
        var: task1 

    - name: Check if Deploy Nginx Template was run
      stat:
        path: /var/www/html/hello-world/index.html
      register: task2

    - name: Print task 2 variable
      debug:
        var: task2

    - name: Add points if Nginx deployment wass successful
      ansible.builtin.set_fact:
        student_score: "{{ student_score|int + 10 }}"
      when: task2.stat.exists

    - debug:
        msg: "Your Score after Task 2 {{ student_score }}"

    - name: Check if nginx is installed
      command: rpm - qa | grep nginx
      register: task3
      ignore_errors: True

    - name: Print task 3 variable
      debug:
        var: task3
