---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Start score sum
      ansible.builtin.set_fact:
        student_score: 0


    - name: Get Deploy Nginx job template ID
      ansible.controller.job_template:
        name: "Hufflepuff Deploy Nginx {{ awx_user_name }}" 
        state: exists
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
      register: task2

     - name: Print task 2 variable
       debug:
         var: task2


     - name: Get Remove Nginx job template ID
       ansible.controller.job_template:
         name: "Hufflepuff Remove Nginx {{ awx_user_name }}"
         state: exists
         controller_host: "{{ controller_host }}"
         controller_username: "{{ controller_username }}"
         controller_password: "{{ controller_password }}"
         validate_certs: false
       register: task2

     - name: Print task 3 variable
       debug:
         var: task3
