---
- hosts: webservers
  gather_facts: false
  become: true

  tasks:
    - name: Start score sum
      ansible.builtin.set_fact:
        student_score: 0

    - name: Verifying Student webserver exists
      ansible.builtin.command: ping -c 1 "{{ student_webserver }}"
      ignore_unreachable: true
      register: task1

    - name: Print task 1 variable
      debug:
        var: task1 

    - name: Add points if Student webserver exists within webservers group
      ansible.builtin.set_fact:
        student_score: "{{ student_score|int + 5 }}"
      ignore_errors: true
      when: task1.rc == 0

    - debug:
        msg: "Your Score after Task 1 is {{ student_score }}"

    - name: Check if Deploy Nginx Template was run
      stat:
        path: /var/www/html/hello-world/index.html
      ignore_errors: true
      register: task2

    - name: Print task 2 variable
      debug:
        var: task2

    - name: Add points if Nginx deployment was successful
      ansible.builtin.set_fact:
        student_score: "{{ student_score|int + 10 }}"
      when: task2.stat.exists

    - debug:
        msg: "Your Score after Task 2 is {{ student_score }}"

    - name: Check if nginx is installed
      command: rpm - qa | grep nginx
      register: task3
      ignore_errors: True

    - name: Print task 3 variable
      debug:
        var: task3

    - name: Add points if Nginx Removal was successful
      ansible.builtin.set_fact:
        student_score: "{{ student_score|int + 15 }}"
      when: task3.failed

    - debug:
        msg: "Your Score after Task 3 is {{ student_score }}"
