---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Start score sum
      ansible.builtin.set_fact:
        student_score: 0

    - name: Add points if student webserver is part of webservers group
      ansible.builtin.set_fact:
        student_score: "{{ student_score|int + 5 }}

    - debug:
        msg: "Your Score after Task 1: {{ student_score }}"

    - name: Get Deploy Nginx job template ID
      ansible.controller.job_template:
        name: "Hufflepuff Deploy Nginx {{ awx_user_name }}" 
        state: exists
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
      register: task2

#    - name: Print task 2 variable
#      debug:
#        var: task2

    - name: Add points if Nginx deployment was successful
      ansible.builtin.set_fact:
        student_score: "{{ student_score|int + 10 }}"
      when: task2.id is defined

    - debug:
        msg: "Your Score after Task 2: {{ student_score }}"

    - name: Get Remove Nginx job template ID
      ansible.controller.job_template:
        name: "Hufflepuff Remove Nginx {{ awx_user_name }}"
        state: exists
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: false
      register: task3

#    - name: Print task 3 variable
#      debug:
#        var: task3

    - name: Add points if Nginx removal was successful
      ansible.builtin.set_fact:
        student_score: "{{ student_score|int + 15 }}"
      when: task3.id is defined

    - debug:
        msg: "Your Score after Task 3: {{ student_score }}"
