---
- hosts: webservers
  gather_facts: false
  become: true

  tasks:
  - name: Stop Nginx
    service:
      name: nginx
      state: stopped

  - name: Disable nginx service
    service:
      name: nginx
      enabled: false
  
  - name: Remove nginx
    dnf:
      name: nginx
      state: absent 
